const String logoString = 'assets/logo';
const String logo = '$logoString/mslogo.png';
const String random = '$logoString/download.png';
const String testing= '$logoString/testing.jpg';
const String splashGif= '$logoString/splashgif.gif';
const String noDataGif= '$logoString/noData.gif';
const String noData= '$logoString/comp_4.gif';
const String noData1= '$logoString/img.png';
const String hand_touch= '$logoString/hand_touch.png';
